[project]
name = "tools"
version = "0.0.1"
description = "Project tools and scripts"
requires-python = "==3.12.10"
dependencies = [
  "boto3>=1.40.74",
  "sagemaker>=2.256.0,<3.0.0",
]

[dependency-groups]
dev = ["boto3-stubs[s3]>=1.38.0"]

[tool.uv]
package = true
src = ["src"]
