---
name: Rust code checks
run-name: Rust code checks
on:
  pull_request:
jobs:
  detect_changes:
    runs-on: ubuntu-latest
    name: Detect Rust code changes
    permissions:
      pull-requests: read
    outputs:
      rust: ${{ steps.filter.outputs.rust }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            rust:
              - '**/*.rs'
              - '**/Cargo.toml'
              - '**/Cargo.lock'
  run_rust_code_checks:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.rust == 'true' }}
    name: Run Rust code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Flox
        uses: flox/install-flox-action@v2
      - name: Cache Rust build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: rust-ci
          save-if: ${{ github.ref == 'refs/heads/master' }}
      - name: Run Rust code checks
        uses: flox/activate-action@v1
        with:
          command: mask development rust ci
