---
name: Rust code checks
run-name: Rust code checks
on:
  pull_request:
jobs:
  detect_changes:
    runs-on: ubuntu-latest
    name: Detect Rust code changes
    permissions:
      pull-requests: read
    outputs:
      rust: ${{ steps.filter.outputs.rust }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            rust:
              - '**/*.rs'
              - '**/Cargo.toml'
              - '**/Cargo.lock'
  run_rust_code_checks:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.rust == 'true' }}
    name: Run Rust code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Flox
        uses: flox/install-flox-action@v2
      - name: Run Rust code checks
        uses: flox/activate-action@v1
        with:
          command: mask development rust all
      - name: Upload Rust coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: .coverage_output/rust.xml
          flag-name: rust
          parallel: false
